---
- name: Retrieve {{ SERVICE_NAME }} configuration
  shell: >
    oc get configmaps/{{ crc_svc_config_alias }}
    -n {{ namespace }}
    -o jsonpath='{.data.config}'
  register: svc_json_str_config

- name: Validate CRC JSON config
  set_fact: svc_json_config={{ svc_json_str_config.stdout | from_json }}
  register: crc_json_config_valid
  ignore_errors: True

- block:
  - asb_last_operation:
      description: "config was not valid json. Could not bind"

  - lineinfile:
      line: 'config was not valid json. Could not bind'
      path: '{{ crc_term_msg_filepath }}'
      unsafe_writes: true

  - fail:
      msg: "config was not valid json. Could not bind"
  when: crc_json_config_valid.failed

- name: Creating CRC {{ CLIENT_ID }} secret
  k8s_v1_secret:
    name: '{{ crc_client_config_alias }}'
    namespace: '{{ namespace }}'
    annotations:
      configType: '{{ crc_svc_config_type }}'
    labels:
      name: '{{ SERVICE_NAME }}'
      mobile: '{{ crc_svc_label_mobile }}'
      serviceName: '{{ crc_svc_name }}'
      serviceInstanceID: '{{ _apb_service_instance_id }}'
      mobileClientId: '{{ CLIENT_ID }}'
      mobile-client: "enabled"
    string_data:
      type: '{{ crc_svc_type }}'
      name: '{{ SERVICE_NAME }}'
      uri: '{{ SERVICE_URI }}'
      config: '{{ svc_json_config | to_nice_json }}'

- asb_encode_binding:
    fields:
      CLIENT_ID: "{{ CLIENT_ID }}"
  when: encode_asb_binding