- name: Validate CRC JSON config
  set_fact: svc_json_config={{ SERVICE_CONFIG | from_json }}
  register: crc_json_config_valid
  ignore_errors: True

- fail:
    msg: |
      Failed to validate provided JSON configuration
      CRC with invalid JSON config can not be created
  when: crc_json_config_valid|failed

- name: Save CRC secrets
  k8s_v1_secret:
    name: '{{ SERVICE_NAME | lower }}'
    namespace: '{{ namespace }}'
    labels:
      name: '{{ SERVICE_NAME }}'
      mobile: enabled
      serviceName: '{{ SERVICE_NAME }}'
    string_data:
      type: 'Custom Runtime Connector'
      name: '{{ SERVICE_NAME }}'
      uri: '{{ SERVICE_URI }}'

- name: Creating CRC configmap
  k8s_v1_config_map:
    name: '{{ SERVICE_NAME | lower }}'
    namespace: '{{ namespace }}'
    labels:
      name: '{{ SERVICE_NAME }}'
      mobile: enabled
      serviceName: '{{ SERVICE_NAME }}'
    data:
      type: 'Custom Runtime Connector'
      name: '{{ SERVICE_NAME }}'
      uri: '{{ SERVICE_URI }}'
      config: '{{ svc_json_config | to_nice_json }}'