---
- name: Test|Check that {{ crc_svc_config_alias }} secret has been removed
  shell: oc get secret --namespace={{ namespace }} {{ crc_svc_config_alias }} 2>&1
  register: result
  retries: 50
  delay: 2
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'

- name: Test|Check that {{ crc_svc_config_alias }} configmap has been removed
  shell: oc get configmaps --namespace={{ namespace }} {{ crc_svc_config_alias }} 2>&1
  register: result
  retries: 50
  delay: 2
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'