---
- name: Test|Check that CRC secret exists
  shell: oc get secret --namespace={{ namespace }} -o name {{ crc_svc_config_alias }} 2>&1
  register: crc_secret_exists
  failed_when: crc_svc_config_alias not in crc_secret_exists.stdout

- name: Test|Get the created CRC {{ crc_svc_config_name }} configmap
  shell: oc get configmap --namespace={{ namespace }} -o name {{ crc_svc_config_alias }} 2>&1
  register: crc_configmap_exists
  failed_when: crc_svc_config_alias not in crc_configmap_exists.stdout