---
- name: Delete CRC secrets
  k8s_v1_secret:
    name: '{{ crc_svc_config_alias }}'
    namespace: '{{ namespace }}'
    state: absent

- name: Delete CRC configmap
  k8s_v1_config_map:
    name: '{{ crc_svc_config_alias }}'
    namespace: '{{ namespace }}'
    state: absent