---
- block:
  - asb_last_operation:
      description: '{{ message }}'

  - lineinfile:
      dest: '{{ crc_term_msg_filepath }}'
      regexp: '^'
      line: '{{ message }}'
      state: present
      unsafe_writes: yes

  - fail:
      msg: "{{ message }}"
    when: result.failed

  when: result is defined